import QueryClientProviderClient from "@/provider/query-client-provider";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <QueryClientProviderClient>
        {children}
        <Toaster position="top-center" richColors/>
        </QueryClientProviderClient>
        </body>
    </html>
  );
}
